# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# version: 2
# updates:
#   - package-ecosystem: "npm" # See documentation for possible values
#     directory: "react" # Location of package manifests
#     schedule:
#       interval: "weekly"
#   - package-ecosystem: "nuget" # See documentation for possible values
#     directories:
#       - "dotnet-with-react/API" # Location of package manifests
#       - "dotnet-with-react/tests"
#     schedule:
#       interval: "weekly"

version: 2
updates:
  - package-ecosystem: nuget
    directory: "/dotnet-with-react"
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(backend)"

  - package-ecosystem: "npm"
    directory: "/react"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "eslint-*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(frontend)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker)"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(actions)"
    groups:
      actions-dependencies:
        patterns:
          - "*"