name: Build and Run tests

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Hello World Github Actions"
